[package]
name = "emma65-vscode-adapter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "emma65-vscode-adapter"
path = "src/main.rs"

[dependencies]
emma65 = { path = "../.." }
dap = "0.4.1-alpha1"
tokio = { version = "1", features = ["rt"] }
base64 = "0.22"
figment = { version = "0.10", features = ["toml", "env"] }
